services:
  ckan:
    image: ckan/ckan-base:${CKAN_VERSION:-2.11}
    container_name: ckan
    environment:
      - CKAN_SITE_URL=${CKANR_DEFAULT_URL:-http://localhost:5000}
      - CKAN__PLUGINS=${CKAN__PLUGINS}
      - CKAN__AUTH__ALLOW_DATASET_COLLABORATORS=${CKAN__AUTH__ALLOW_DATASET_COLLABORATORS}
      - CKAN_SQLALCHEMY_URL=postgresql://ckan_default:pass@postgres/ckan_test
      - CKAN_DATASTORE_WRITE_URL=postgresql://datastore_write:pass@postgres/datastore_test
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_read:pass@postgres/datastore_test
      - CKAN_SOLR_URL=${SOLR_URL:-http://solr:8983/solr/ckan}
      - CKAN_REDIS_URL=${REDIS_URL:-redis://redis:6379/1}
      # - CKAN_DATAPUSHER_URL=${DATAPUSHER_URL:-http://datapusher:8800}
      # - CKAN__DATAPUSHER__CALLBACK_URL_BASE=${CKANR_DEFAULT_URL:-http://localhost:5000}
      # - CKAN__DATAPUSHER__API_TOKEN=${CKAN__DATAPUSHER__API_TOKEN}
      - TZ=UTC
      - CKAN_SYSADMIN_NAME=ckan_admin
      - CKAN_SYSADMIN_PASSWORD=test1234
      - CKAN_SYSADMIN_EMAIL=mail@example.com
      - CKAN___BEAKER__SESSION__SECRET=secret
      - CKAN__ACTIVITY_STREAMS__EMAIL_NOTIFICATIONS=true
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "${CKANR_DEFAULT_URL:-http://localhost:5000}/api/action/status_show"]
      interval: 60s
      timeout: 30s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: ckan/ckan-postgres-dev:${CKAN_PG_VERSION:-2.11}
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - CKAN_DB_USER=ckan_default
      - CKAN_DB_PASSWORD=pass
      - CKAN_DB=ckan_test
      - DATASTORE_READONLY_USER=datastore_read
      - DATASTORE_READONLY_PASSWORD=pass
      - DATASTORE_DB=datastore_test
      - CKAN_VERSION=${CKAN_VERSION:-2.11}
    restart: unless-stopped
    healthcheck:
      test: ["CMD","pg_isready","-U","ckan_default","-d","ckan_test"]
      interval: 30s
      timeout: 10s
      retries: 5

  solr:
    image: ckan/ckan-solr:${SOLR_VERSION:-2.10-solr9-spatial}
    container_name: solr
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "${SOLR_URL:-http://localhost:8983/solr/ckan/admin/ping?wt=json&distrib=false}"]
      interval: 60s
      timeout: 10s
      retries: 3

  redis:
    image: redis:6
    container_name: redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]
