services:
  app:
    # image: mcr.microsoft.com/devcontainers/base:noble
    container_name: app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    networks:
      - webnet
      - ckannet
      - solrnet
      - redisnet
      - dbnet

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    security_opt:
      - apparmor=docker-default

  # See https://github.com/ckan/ckan-docker/blob/master/docker-compose.yml
  ckan:
    image: ckan/ckan-base:${CKAN_VERSION:-2.11}
    container_name: ckan
    environment:
      - CKAN_SITE_URL=${CKAN_PUBLIC_URL:-http://localhost:5000}
      - CKAN__PLUGINS=${CKAN__PLUGINS}
      - CKAN_SQLALCHEMY_URL=postgresql://ckan_default:pass@postgres/ckan_test
      - CKAN_DATASTORE_WRITE_URL=postgresql://datastore_write:pass@postgres/datastore_test
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_read:pass@postgres/datastore_test
      - CKAN_SOLR_URL=${SOLR_URL:-http://solr:8983/solr/ckan}
      - CKAN_REDIS_URL=${REDIS_URL:-redis://redis:6379/1}
      - CKAN_DATAPUSHER_URL=${DATAPUSHER_URL:-http://datapusher:8800}
      - CKAN__DATAPUSHER__CALLBACK_URL_BASE=${CKAN_INTERNAL_URL:-http://ckan:5000}
      - TZ=UTC
      - CKAN_SYSADMIN_NAME=ckan_admin
      - CKAN_SYSADMIN_PASSWORD=test1234
      - CKAN_SYSADMIN_EMAIL=mail@example.com
      - CKAN___BEAKER__SESSION__SECRET=secret
      - CKAN__ACTIVITY_STREAMS__EMAIL_NOTIFICATIONS=true
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "${CKAN_INTERNAL_URL:-http://ckan:5000}/api/action/status_show"]
      interval: 60s
      timeout: 30s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ckannet
      - dbnet
      - solrnet
      - redisnet

  postgres:
    image: ckan/ckan-postgres-dev:${CKAN_PG_VERSION:-2.11}
    container_name: postgres
    environment:
      - CKAN_VERSION=${CKAN_VERSION:-2.11}
    networks:
      - dbnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD","pg_isready","-U","ckan_default","-d","ckan_test"]
      interval: 30s
      timeout: 10s
      retries: 5

  datapusher:
    image: ckan/ckan-base-datapusher:${DATAPUSHER_VERSION:-0.0.21}
    container_name: datapusher
    environment:
      - DATAPUSHER_MAX_CONTENT_LENGTH=10485760
      - DATAPUSHER_CHUNK_SIZE=16384
      - DATAPUSHER_CHUNK_INSERT_ROWS=250
      - DATAPUSHER_DOWNLOAD_TIMEOUT=30
      - DATAPUSHER_SSL_VERIFY=False
    networks:
      - ckannet
      - dbnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "${DATAPUSHER_URL:-http://datapusher:8800}"]
      interval: 60s
      timeout: 10s
      retries: 3

  solr:
    image: ckan/ckan-solr:${SOLR_VERSION:-2.10-solr9-spatial}
    container_name: solr
    networks:
      - solrnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "${SOLR_URL:-http://localhost:8983/solr/ckan/admin/ping?wt=json&distrib=false}"]
      interval: 60s
      timeout: 10s
      retries: 3

  redis:
    image: redis:6
    container_name: redis
    networks:
      - redisnet
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]

networks:
  webnet:
  ckannet:
  solrnet:
  dbnet:
  redisnet:
