services:
  app:
    # image: mcr.microsoft.com/devcontainers/base:noble
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: service:ckan

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    security_opt:
      - apparmor=docker-default
      # This prevents running sudo in the container
      # - no-new-privileges=true

  ckan:
    image: ckan/ckan-base:${CKAN_VERSION:-2.11}
    container_name: ckan
    environment:
      - CKAN_SITE_URL=${CKANR_DEFAULT_URL:-http://localhost:5000}
      - CKAN__PLUGINS=${CKAN__PLUGINS}
      - CKAN_SQLALCHEMY_URL=postgresql://ckan_default:pass@postgres/ckan_test
      - CKAN_DATASTORE_WRITE_URL=postgresql://datastore_write:pass@postgres/datastore_test
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_read:pass@postgres/datastore_test
      - CKAN_SOLR_URL=${SOLR_URL:-http://solr:8983/solr/ckan}
      - CKAN_REDIS_URL=${REDIS_URL:-redis://redis:6379/1}
      - CKAN_DATAPUSHER_URL=${DATAPUSHER_URL:-http://datapusher:8000}
      - CKAN__DATAPUSHER__CALLBACK_URL_BASE=${CKANR_DEFAULT_URL:-http://localhost:5000}
      - TZ=UTC
      - CKAN_SYSADMIN_NAME=ckan_admin
      - CKAN_SYSADMIN_PASSWORD=test1234
      - CKAN_SYSADMIN_EMAIL=mail@example.com
      - CKAN___BEAKER__SESSION__SECRET=secret
      - CKAN__ACTIVITY_STREAMS__EMAIL_NOTIFICATIONS=true
    ports:
      - "5000:5000"
  postgres:
    image: ckan/ckan-postgres-dev:${CKAN_PG_VERSION:-2.11}
    container_name: postgres
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  datapusher:
    image: ghcr.io/keitaroinc/datapusher:${DATAPUSHER_VERSION:-0.0.21}
    container_name: datapusher
    environment:
      - DATAPUSHER_MAX_CONTENT_LENGTH=10485760
      - DATAPUSHER_CHUNK_SIZE=16384
      - DATAPUSHER_CHUNK_INSERT_ROWS=250
      - DATAPUSHER_DOWNLOAD_TIMEOUT=30
      - DATAPUSHER_SSL_VERIFY=False
  solr:
    image: ckan/ckan-solr:${SOLR_VERSION:-2.10-solr9-spatial}
    container_name: solr
  redis:
    image: redis:5.0.14
    container_name: redis
