volumes:
  ckan_storage:
  pg_data:
  solr_data:
  # pip_cache:
  # site_packages:
  # local_bin:
  # home_dir:

services:
  app:
    # image: mcr.microsoft.com/devcontainers/base:noble
    container_name: app
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ../..:/workspaces:cached

    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity
    network_mode: service:ckan

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

    security_opt:
      - apparmor=docker-default

  # See https://github.com/ckan/ckan-docker/blob/master/docker-compose.yml
  ckan:
    image: ckan/ckan-base:${CKAN_VERSION:-2.11}
    container_name: ckan
    environment:
      - CKAN_SITE_URL=${CKANR_DEFAULT_URL:-http://localhost:5000}
      - CKAN__PLUGINS=${CKAN__PLUGINS}
      - CKAN__AUTH__ALLOW_DATASET_COLLABORATORS=${CKAN__AUTH__ALLOW_DATASET_COLLABORATORS}
      - CKAN__ACTIVITY_STREAMS_EMAIL_NOTIFICATIONS=${CKAN__ACTIVITY_STREAMS_EMAIL_NOTIFICATIONS}
      - CKAN_SQLALCHEMY_URL=postgresql://ckan_default:pass@postgres/ckan_test
      - CKAN_DATASTORE_WRITE_URL=postgresql://datastore_write:pass@postgres/datastore_test
      - CKAN_DATASTORE_READ_URL=postgresql://datastore_read:pass@postgres/datastore_test
      - CKAN_SOLR_URL=${SOLR_URL:-http://solr:8983/solr/ckan}
      - CKAN_REDIS_URL=${REDIS_URL:-redis://redis:6379/1}
      # - CKAN_DATAPUSHER_URL=${DATAPUSHER_URL:-http://datapusher:8800}
      # - CKAN__DATAPUSHER__CALLBACK_URL_BASE=${CKANR_DEFAULT_URL:-http://localhost:5000}
      # - CKAN__DATAPUSHER__API_TOKEN=${CKAN__DATAPUSHER__API_TOKEN}
      - TZ=UTC
      - CKAN_SYSADMIN_NAME=ckan_admin
      - CKAN_SYSADMIN_PASSWORD=test1234
      - CKAN_SYSADMIN_EMAIL=mail@example.com
      - CKAN___BEAKER__SESSION__SECRET=secret
      - CKAN__ACTIVITY_STREAMS__EMAIL_NOTIFICATIONS=true
    volumes:
      - ckan_storage:/var/lib/ckan
      # - ./src:/srv/app/src_extensions
      # - pip_cache:/root/.cache/pip
      # - site_packages:/usr/local/lib/python3.10/site-packages
      # - local_bin:/usr/local/bin
      # - home_dir:/srv/app/
    ports:
      - "5000:5000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "${CKANR_DEFAULT_URL:-http://localhost:5000}/api/action/status_show"]
      interval: 60s
      timeout: 30s
      retries: 5
    depends_on:
      postgres:
        condition: service_healthy
      solr:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: ckan/ckan-postgres-dev:${CKAN_PG_VERSION:-2.11}
    container_name: postgres
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - CKAN_DB_USER
      - CKAN_DB_PASSWORD
      - CKAN_DB
      - DATASTORE_READONLY_USER
      - DATASTORE_READONLY_PASSWORD
      - DATASTORE_DB
      - CKAN_VERSION=${CKAN_VERSION:-2.11}
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD","pg_isready","-U","ckan_default","-d","ckan_test"]
      interval: 30s
      timeout: 10s
      retries: 5

  solr:
    image: ckan/ckan-solr:${SOLR_VERSION:-2.10-solr9-spatial}
    container_name: solr
    volumes:
      - solr_data:/var/solr
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO", "/dev/null", "${SOLR_URL:-http://localhost:8983/solr/ckan/admin/ping?wt=json&distrib=false}"]
      interval: 60s
      timeout: 10s
      retries: 3

  redis:
    image: redis:6
    container_name: redis
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "-e", "QUIT"]
